//
//  GeocodeResponse.swift
//  LocationGeocodingPOC
//
//  Created by Mamadou Balde on 7/22/26.
//

import Foundation

/// The top-level response payload received from a GIS geocoding service.
struct GeocodeResponse: Codable, Hashable {
    
    /// The absolute network endpoint URL used to generate this response, if tracked.
    var requestURL: String?
    
    /// Spatial reference definition indicating the map coordinate projection system used.
    let spatialReference: SpatialReference
    
    /// An array containing all matches and matched address details generated by the engine.
    let locations: [GeocodeLocation]
    
    enum CodingKeys: String, CodingKey {
        case spatialReference
        case locations
    }
}

/// A representation of a geospatial coordinate system identification.
struct SpatialReference: Codable, Hashable {
    
    /// The primary Well-Known ID (WKID) defining the coordinate system.
    ///
    /// For example, `4326` represents WGS 84 (GPS standard decimal degrees),
    /// while `3857` represents Web Mercator (flat screen projection).
    let wkid: Int
    
    /// The most recent or updated Well-Known ID for this reference system.
    ///
    /// This may match the primary `wkid` or provide a corrected variant
    /// preferred by newer mapping engines.
    let latestWkid: Int
}

/// A structure capturing a singular location candidate found by the geocoding service.
struct GeocodeLocation: Codable, Hashable {
    
    /// The human-readable normalized street address found by the engine.
    let address: String
    
    /// The exact geometric spatial point mapping this location on earth.
    let location: CoordinatePoint
    
    /// A confidence metric rating out of 100 representing the exactness of the address match.
    let score: Int
    
    /// Extended meta attributes containing regional and operational data about the point.
    let attributes: GeocodeAttributes
    
    enum CodingKeys: String, CodingKey {
        case address
        case location
        case score
        case attributes
    }
    
    /// Decodes a geocode location with structural type fallbacks.
    ///
    /// If the server completely omits the root `address` key, a default fallback is
    /// applied to protect the app from breaking.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        self.address = try container.decodeIfPresent(String.self, forKey: .address) ?? "Unknown Match Address"
        self.location = try container.decode(CoordinatePoint.self, forKey: .location)
        self.score = try container.decode(Int.self, forKey: .score)
        self.attributes = try container.decode(GeocodeAttributes.self, forKey: .attributes)
    }
}

/// A lightweight geographic vertex tracking a 2D coordinate on a map grid.
struct CoordinatePoint: Codable, Hashable {
    
    /// The longitude or horizontal grid value (often maps to a X line).
    let x: Double
    
    /// The latitude or vertical grid value (often maps to a Y line).
    let y: Double
}

/// A comprehensive collection of structural and regional metadata parameters returned with a location match.
struct GeocodeAttributes: Codable, Hashable {
    
    /// The unique system-level tracking index sequence identifier for the record result.
    let resultID: Int
    
    /// The identifier of the specific geocoding engine or locator file that matched the row.
    let locName: String
    
    /// The alignment matching index code status (e.g., "M" for match, "U" for unmatched).
    let status: String
    
    /// The computational accuracy score evaluating the parsed address match.
    let score: Int
    
    /// The primary standard address string generated by the indexing database.
    let matchAddr: String
    
    /// A fully extended descriptive label string commonly used for display listings.
    let longLabel: String
    
    /// A compressed address label string used for compact layout interfaces.
    let shortLabel: String
    
    /// The classification taxonomy of the location match (e.g., StreetAddress, PointAddress).
    let type: String
    
    /// The localized municipality or municipality zone classification assigned to the record.
    let city: String
    
    /// The local county or sub-provincial administrative zone classification assigned to the record.
    let subregion: String
    
    /// The state or primary jurisdictional province assignment.
    let region: String
    
    /// The full structural sovereign country title associated with the location coordinates.
    let countryName: String
    
    enum CodingKeys: String, CodingKey {
        case resultID = "ResultID"
        case locName = "Loc_name"
        case status = "Status"
        case score = "Score"
        case matchAddr = "Match_addr"
        case longLabel = "LongLabel"
        case shortLabel = "ShortLabel"
        case type = "Type"
        case city = "City"
        case subregion = "Subregion"
        case region = "Region"
        case countryName = "CntryName"
    }
    
    /// Decodes geocoding attributes while providing safe string fallbacks to prevent runtime decoding errors.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        self.resultID = try container.decode(Int.self, forKey: .resultID)
        self.score = try container.decode(Int.self, forKey: .score)
        
        self.locName = try container.decodeIfPresent(String.self, forKey: .locName) ?? "NYS_Geocoder"
        self.status = try container.decodeIfPresent(String.self, forKey: .status) ?? "U"
        self.matchAddr = try container.decodeIfPresent(String.self, forKey: .matchAddr) ?? "Unmatched Area"
        self.longLabel = try container.decodeIfPresent(String.self, forKey: .longLabel) ?? ""
        self.shortLabel = try container.decodeIfPresent(String.self, forKey: .shortLabel) ?? ""
        self.type = try container.decodeIfPresent(String.self, forKey: .type) ?? "Unknown Type"
        self.city = try container.decodeIfPresent(String.self, forKey: .city) ?? "Out of State"
        self.subregion = try container.decodeIfPresent(String.self, forKey: .subregion) ?? "Unknown Subregion"
        self.region = try container.decodeIfPresent(String.self, forKey: .region) ?? "Unknown Region"
        self.countryName = try container.decodeIfPresent(String.self, forKey: .countryName) ?? "USA"
    }
}
