//
//  GeocodeServerError.swift
//  LocationGeocodingPOC
//
//  Created by Mamadou Balde on 7/22/26.
//

import Foundation

/// The structural error response payload decoded when a GIS geocoding endpoint rejects a request transaction.
struct GeocodeServerError: Codable {
    
    /// The granular error breakdown payload returned by the host mapping engine.
    let error: ErrorDetails
    
    /// A structured container mapping the exact failure details generated by the remote geocoding backend.
    struct ErrorDetails: Codable {
        
        /// The primary system-level machine failure identifier code integer.
        let code: Int
        
        /// An optional precise secondary lookup tracking error code index.
        let extendedCode: Int?
        
        /// A descriptive human-readable failure report message outlining why the process failed.
        let message: String
        
        /// An optional array containing detailed contextual strings explaining underlying data errors.
        let details: [String]?
    }
}
